blank_issues_enabled: false
contact_links:
  - name: Discussion / 讨论区
    url: https://github.com/bobevans-commits/singbox-pro-max-ultra/discussions
    about: Ask questions and discuss with the community / 提问和社区讨论
  - name: Documentation / 文档
    url: https://github.com/bobevans-commits/singbox-pro-max-ultra/wiki
    about: Check the documentation before opening an issue / 提交 Issue 前请先查看文档
